export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";

export const GET_FRIEND_REQUESTS_REQUEST = "GET_FRIEND_REQUESTS_REQUEST";
export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS";
export const GET_FRIEND_REQUESTS_FAIL = "GET_FRIEND_REQUESTS_FAIL";

export const ADD_FRIEND_REQUEST_REQUEST = "ADD_FRIEND_REQUEST_REQUEST";
export const ADD_FRIEND_REQUEST_SUCCESS = "ADD_FRIEND_REQUEST_SUCCESS";
export const ADD_FRIEND_REQUEST_FAIL = "ADD_FRIEND_REQUEST_FAIL";

export const DELETE_FRIEND_REQUEST = "DELETE_FRIEND_REQUEST";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL";

export const ACCEPT_FRIEND_REQUEST_REQUEST = "ACCEPT_FRIEND_REQUEST_REQUEST";
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAIL = "ACCEPT_FRIEND_REQUEST_FAIL";
