export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_FAIL";

export const GET_FRIEND_REQUESTS_REQUEST = "GET_FRIEND_REQUESTS_REQUEST";
export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS";
export const GET_FRIEND_REQUESTS_FAIL = "GET_FRIEND_REQUESTS_FAIL";

export const TOGGLE_SEND_FRIEND_REQUEST_REQUEST =
  "TOGGLE_SEND_FRIEND_REQUEST_REQUEST";
export const TOGGLE_SEND_FRIEND_REQUEST_SUCCESS =
  "TOGGLE_SEND_FRIEND_REQUEST_SUCCESS";
export const TOGGLE_SEND_FRIEND_REQUEST_FAIL =
  "TOGGLE_SEND_FRIEND_REQUEST_FAIL";

export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAIL = "REMOVE_FRIEND_FAIL";

export const ACCEPT_FRIEND_REQUEST_REQUEST = "ACCEPT_FRIEND_REQUEST_REQUEST";
export const ACCEPT_FRIEND_REQUEST_SUCCESS = "ACCEPT_FRIEND_REQUEST_SUCCESS";
export const ACCEPT_FRIEND_REQUEST_FAIL = "ACCEPT_FRIEND_REQUEST_FAIL";

export const REJECT_FRIEND_REQUEST_REQUEST = "REJECT_FRIEND_REQUEST_REQUEST";
export const REJECT_FRIEND_REQUEST_SUCCESS = "REJECT_FRIEND_REQUEST_SUCCESS";
export const REJECT_FRIEND_REQUEST_FAIL = "REJECT_FRIEND_REQUEST_FAIL";
