export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

export const SEND_MESSAGE_TO_GROUP_REQUEST = "SEND_MESSAGE_TO_GROUP_REQUEST";
export const SEND_MESSAGE_TO_GROUP_SUCCESS = "SEND_MESSAGE_TO_GROUP_SUCCESS";
export const SEND_MESSAGE_TO_GROUP_FAIL = "SEND_MESSAGE_TO_GROUP_FAIL";

export const GET_GROUP_MESSAGES_REQUEST = "GET_GROUP_MESSAGES_REQUEST";
export const GET_GROUP_MESSAGES_SUCCESS = "GET_GROUP_MESSAGES_SUCCESS";
export const GET_GROUP_MESSAGES_FAIL = "GET_GROUP_MESSAGES_FAIL";
