export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const GET_GROUPS_REQUEST = "GET_GROUPS_REQUEST";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAIL = "GET_GROUPS_FAIL";

export const SEND_MESSAGE_TO_GROUP_REQUEST = "SEND_MESSAGE_TO_GROUP_REQUEST";
export const SEND_MESSAGE_TO_GROUP_SUCCESS = "SEND_MESSAGE_TO_GROUP_SUCCESS";
export const SEND_MESSAGE_TO_GROUP_FAIL = "SEND_MESSAGE_TO_GROUP_FAIL";

export const GET_GROUP_MESSAGES_REQUEST = "GET_GROUP_MESSAGES_REQUEST";
export const GET_GROUP_MESSAGES_SUCCESS = "GET_GROUP_MESSAGES_SUCCESS";
export const GET_GROUP_MESSAGES_FAIL = "GET_GROUP_MESSAGES_FAIL";

export const UPDATE_GROUP_MESSAGE_STATUS_REQUEST =
  "UPDATE_GROUP_MESSAGE_STATUS_REQUEST";
export const UPDATE_GROUP_MESSAGE_STATUS_SUCCESS =
  "UPDATE_GROUP_MESSAGE_STATUS_SUCCESS";
export const UPDATE_GROUP_MESSAGE_STATUS_FAIL =
  "UPDATE_GROUP_MESSAGE_STATUS_FAIL";

export const DELETE_GROUP_MESSAGE_REQUEST = "DELETE_GROUP_MESSAGE_REQUEST";
export const DELETE_GROUP_MESSAGE_SUCCESS = "DELETE_GROUP_MESSAGE_SUCCESS";
export const DELETE_GROUP_MESSAGE_FAIL = "DELETE_GROUP_MESSAGE_FAIL";
